# Generated by Django 4.1.6 on 2023-02-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.TextField(max_length=30)),
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('pw', models.TextField()),
                ('phonenum', models.IntegerField(max_length=40)),
                ('schoolssn', models.IntegerField(max_length=40)),
            ],
        ),
    ]
