# Generated by Django 4.1.6 on 2023-02-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_phonenum_alter_user_schoolssn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phonenum',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='schoolssn',
            field=models.CharField(max_length=30),
        ),
    ]
