# Generated by Django 4.1.6 on 2023-03-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_phonenum_alter_user_schoolssn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='schoolssn',
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
