# Generated by Django 4.1.6 on 2023-04-03 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_spoteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRealation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sportevent', models.TextField(max_length=20)),
                ('username', models.TextField(max_length=10)),
                ('position', models.TextField(max_length=20)),
                ('manager', models.BooleanField(default=False)),
                ('rank', models.TextField(max_length=20)),
                ('teamname', models.ForeignKey(db_column='teamname', on_delete=django.db.models.deletion.CASCADE, to='user.spoteam')),
                ('userid', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
